// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/catalog/events": {
            "get": {
                "tags": [
                    "catalog"
                ],
                "summary": "List events",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "active",
                        "name": "active",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "closed",
                        "name": "closed",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "slug",
                        "name": "slug",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "title",
                        "name": "title",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order by field",
                        "name": "order_by",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "ascending",
                        "name": "ascending",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.apiResponse"
                        }
                    }
                }
            }
        },
        "/api/catalog/events/realtime": {
            "get": {
                "tags": [
                    "catalog"
                ],
                "summary": "Get realtime data for an event by slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "event slug",
                        "name": "slug",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.apiResponse"
                        }
                    }
                }
            }
        },
        "/api/catalog/markets": {
            "get": {
                "tags": [
                    "catalog"
                ],
                "summary": "List markets",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "active",
                        "name": "active",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "closed",
                        "name": "closed",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "event id",
                        "name": "event_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "slug",
                        "name": "slug",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "question contains",
                        "name": "question",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order by field",
                        "name": "order_by",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "ascending",
                        "name": "ascending",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.apiResponse"
                        }
                    }
                }
            }
        },
        "/api/catalog/markets/realtime": {
            "get": {
                "tags": [
                    "catalog"
                ],
                "summary": "Get realtime data for a market by slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "market slug",
                        "name": "slug",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.apiResponse"
                        }
                    }
                }
            }
        },
        "/api/catalog/sync": {
            "post": {
                "tags": [
                    "catalog"
                ],
                "summary": "Run catalog sync",
                "parameters": [
                    {
                        "type": "string",
                        "description": "sync scope (events|markets|series|tags|all)",
                        "name": "scope",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "max pages",
                        "name": "max_pages",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "resume from cursor",
                        "name": "resume",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "tag id",
                        "name": "tag_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "open|closed",
                        "name": "closed",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "max assets for /book resync",
                        "name": "book_max_assets",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "batch size for /book resync",
                        "name": "book_batch_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sleep per batch (e.g. 2s)",
                        "name": "book_sleep_per_batch",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.apiResponse"
                        }
                    }
                }
            }
        },
        "/api/catalog/sync-state": {
            "get": {
                "tags": [
                    "catalog"
                ],
                "summary": "List sync states",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.apiResponse"
                        }
                    }
                }
            }
        },
        "/api/catalog/tokens": {
            "get": {
                "tags": [
                    "catalog"
                ],
                "summary": "List tokens",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "market id",
                        "name": "market_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "outcome",
                        "name": "outcome",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "side",
                        "name": "side",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order by field",
                        "name": "order_by",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "ascending",
                        "name": "ascending",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.apiResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "tags": [
                    "health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.apiResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                },
                "meta": {
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
