export const DEFAULTS = {
  PAGE_LIMIT: 100,
  LABEL_PAGE_LIMIT: 200,
  OPPORTUNITY_PAGE_LIMIT: 50,
  MIN_EDGE: "0.05",
  MIN_CONFIDENCE: "0.8",
  STOP_LOSS_PCT: "0.10",
  TAKE_PROFIT_PCT: "0.20",
  MAX_HOLD_HOURS: 72,
  MAX_DAILY_TRADES: 10,
} as const;

